'use client';
import { ProtectedPage } from '@/components/ProtectedPage';

export default function EpargneLayout({ children }: { children: React.ReactNode }) {
    return (
        <ProtectedPage requiredAuthorities={['EPARGNE_VIEW', 'EPARGNE_CREATE', 'EPARGNE_UPDATE', 'EPARGNE_DELETE', 'EPARGNE_VALIDATE', 'EPARGNE_CLOSE', 'EPARGNE_REPORT', 'EPARGNE_SETTINGS', 'EPARGNE_DAILY_CLOSING', 'ACCOUNTING_CASH_MANAGEMENT', 'GUICHET_CAISSE', 'CAISSE_VALIDATE_CLOSING', 'EPARGNE_FEE_EXECUTE', 'EPARGNE_VIREMENT_BATCH_CREATE', 'EPARGNE_VIREMENT_BATCH_VALIDATE', 'EPARGNE_CHECKBOOK_CREATE', 'EPARGNE_CHECKBOOK_VALIDATE', 'EPARGNE_CHECKBOOK_RECEIVE', 'EPARGNE_CHECKBOOK_DELIVER', 'EPARGNE_STATEMENT_CREATE', 'EPARGNE_STATEMENT_VALIDATE', 'EPARGNE_STATEMENT_DELIVER']}>
            {children}
        </ProtectedPage>
    );
}
