export class StkArticle {
    articleId: string | null;
    codeArticle: string;
    magasinId: string;
    libelle: string;
    sousCategorieId: string;
    conditionnement: string | null;
    uniteId: string | null;
    catalogue: string | null;
    qteStock: number;
    description: string | null;
    seuil: number | null;
    seuilMax: number | null;
    pump: number | null;
    qtePhysique: number;
    consomme: number | null;
    prixVente: number | null;
    compteStock: string | null;
    compteCharge: string | null;
    peremption: boolean;
    lot: boolean;
    caseId: string | null;
    numeroOrdre: number;
    userCreation: string;
    dateCreation: Date | null;
    userUpdate: string | null;
    dateUpdate: string | null;
    compteService: string | null;
    libelleCompte: string | null;
    codeDomaine: string | null;
    serviceId: string | null;
    prixUnitaire: number | null;
    tauxRemboursement: number | null;
    coefficient: string | null;
    montantFiche: number | null;
    compteCash: string | null;
    dateTarif: Date | null;
    codeCategorie: string | null;
    categorie: string | null;
    prixAnestesieProg: number | null;
    prixAnestesieUrg: string | null;
    prixAnestesieEnf: number | null;
    prixAnestesieEnfUrg: number | null;
    prixAnestesieEnfP: number | null;
    pAU: number | null;
    visible: boolean | null;
    pUMPMVT: number | null;
    pUMPFin: number | null;

    constructor() {
        this.articleId = null;
        this.codeArticle = "";
        this.magasinId = "";
        this.libelle = "";
        this.sousCategorieId = "";
        this.conditionnement = null;
        this.uniteId = null;
        this.catalogue = null;
        this.qteStock = 0.00;
        this.description = null;
        this.seuil = 0.00;
        this.seuilMax = 0.00;
        this.pump = 0.00;
        this.qtePhysique = 0;
        this.consomme = 0.00;
        this.prixVente = 0;
        this.compteStock = null;
        this.compteCharge = null;
        this.peremption = false;
        this.lot = false;
        this.caseId = null;
        this.numeroOrdre = 0;
        this.userCreation = "";
        this.dateCreation = null;
        this.userUpdate = null;
        this.dateUpdate = null;
        this.compteService = null;
        this.libelleCompte = null;
        this.codeDomaine = null;
        this.serviceId = null;
        this.prixUnitaire = null;
        this.tauxRemboursement = null;
        this.coefficient = null;
        this.montantFiche = null;
        this.compteCash = null;
        this.dateTarif = null;
        this.codeCategorie = null;
        this.categorie = null;
        this.prixAnestesieProg = 0;
        this.prixAnestesieUrg = null;
        this.prixAnestesieEnf = 0;
        this.prixAnestesieEnfUrg = 0;
        this.prixAnestesieEnfP = 0;
        this.pAU = 0;
        this.visible = null;
        this.pUMPMVT = null;
        this.pUMPFin = null;
    }
}