export class CptEcriture {
  ecritureId: string;
  pieceId: string;
  compteId: string;
  numeroPiece: string;
  journalId: string;
  brouillardId: string;
  reference: string;
  dateEcriture: string;
  debit: number;
  credit: number;
  activiteId: string;
  financementId: string;
  regionId: string;
  facture: string;
  deviseId: string;
  taux: number;
  debitDevise: number;
  creditDevise: number;
  ecritureIdTVA: string;
  valide: boolean;
  rapproche: boolean;
  userCreation: string;
  dateCreation: string;
  dateUpdate: string;
  userUpdate: string;
  exerciceId: string;
  soldeJournal: number;
  soldeCompte: number;
  codeJournal:string;
  codeCompte:string;
  printDate?: string;
  libelle:string;
  constructor() {
    this.ecritureId = '';
    this.pieceId = '';
    this.compteId = '';
    this.numeroPiece = '';
    this.journalId = '';
    this.brouillardId = '';
    this.reference = '';
    this.dateEcriture = '';
    this.debit = 0;
    this.credit = 0;
    this.activiteId = '';
    this.financementId = '';
    this.regionId = '';
    this.facture = '';
    this.deviseId = '';
    this.taux = 0;
    this.debitDevise = 0;
    this.creditDevise = 0;
    this.ecritureIdTVA = '';
    this.valide = false;
    this.rapproche = false;
    this.userCreation = '';
    this.dateCreation = '';
    this.dateUpdate = '';
    this.userUpdate = '';
    this.exerciceId = '';
    this.soldeJournal= 0;
    this.soldeCompte= 0;
    this.codeJournal='';
    this.codeCompte='';
    this.libelle='';
  }
}
