// EnterRSP.ts
export class EnterRSP {
    entreeImportId: string;
    noEntree: number | null;
    noLettreTransport: string;
    recuPalan: string;
    rspInt: number | null;
    nbrePalette: number | null;
    nbreEtiquette: number | null;
    noConteneur: string;
    provenanceId: number | null;
    bargeId: number | null;
    transitaireId: number | null;
    importateurId: number | null;
    nif: string;
    nature: string;
    transporteur: string;
    marchandiseId: number | null;
    emballageId: number | null;
    typeConditionId: string;
    typeTransport: string;
    dateEntree: Date | null;
    nbreColis: number | 0;
    poids: number | 0;
    poidsExonere: number | 0;
    montant: number | 0;
    destinationId: number | null;
    entreposId: number | null;
    peseMagasin: boolean;
    salissage: boolean;
    tauxSalissage: number | 0;
    montantPeseMagasin: number | 0;
    faireSuivre: boolean;
    montantFaireSuivre: number | 0;
    qteLt: number | 0;
    poidsLt: number | 0;
    fraisSlt: number | 0;
    fraisSrsp: number | 0;
    surtaxeCrsp: number | 0;
    surtaxeClt: number | 0;
    surtaxePlt: number | 0;
    surtaxePrsp: number | 0;
    pvId: number | 0;
    penalite: number | 0;
    montantLt: number | 0;
    montantRsp: number | 0;
    taxe: number | 0;
    fraisPompageRsp: number | 0;
    montantCamion: number | 0;
    montantBarge: number | 0;
    tarifCamion: number | 0;
    tarifBarge: number | 0;
    numConteneur: string;
    fraisArrimage: number | 0;
    doubleManut: boolean;
    exonere: boolean;
    transit: boolean;
    dossier: string;
    declarant: string;
    observation: string;
    constatation: string;
    colisManquants: string;
    colisAvaries: string;
    plaque: string;
    dateCreation: Date | null;
    userCreation: string | undefined;
    dateUpdate: Date | null;
    userUpdate: string | undefined;
    surtaxePrspTaux: number | 0;
    constructor();
    constructor(userCreation?: string);
    constructor(userCreation?: string) {
        this.entreeImportId = '';
        this.noEntree = null;
        this.noLettreTransport = '';
        this.recuPalan = '';
        this.rspInt = null;
        this.nbrePalette = null;
        this.nbreEtiquette = null;
        this.noConteneur = '';
        this.provenanceId = null;
        this.bargeId = null;
        this.transitaireId = null;
        this.importateurId = null;
        this.nif = '';
        this.transporteur = '';
        this.marchandiseId = null;
        this.emballageId = null;
        this.typeConditionId = '';
        this.typeTransport = '';
        this.dateEntree = new Date();
        this.nbreColis = null;
        this.poids = 0;
        this.poidsExonere = 0;
        this.montant = 0;
        this.destinationId = null;
        this.entreposId = null;
        this.peseMagasin = false;
        this.montantPeseMagasin = 0;
        this.faireSuivre = false;
        this.salissage = false;
        this.tauxSalissage = 0;
        this.nature = 'lourd';
        this.montantFaireSuivre = 0;
        this.qteLt = 0;
        this.poidsLt = 0;
        this.fraisSlt = 0;
        this.fraisSrsp = 0;
        this.surtaxeCrsp = 0;
        this.surtaxeClt = 0;
        this.surtaxePlt = 0;
        this.surtaxePrsp = 0;
        this.pvId = 0;
        this.penalite = 0;
        this.montantLt = 0;
        this.montantRsp = 0;
        this.taxe = 0;
        this.fraisPompageRsp = 0;
        this.montantCamion = 0;
        this.montantBarge = 0;
        this.tarifCamion = 0;
        this.tarifBarge = 0;
        this.numConteneur = '';
        this.fraisArrimage = 0;
        this.doubleManut = false;
        this.exonere = false;
        this.transit = false;
        this.dossier = '';
        this.declarant = '';
        this.observation = '';
        this.constatation = '';
        this.colisManquants = '';
        this.colisAvaries = '';
        this.plaque = '';
        this.dateCreation = null;
        this.userCreation = userCreation || '';
        this.dateUpdate = null;
        this.userUpdate = '';
        this.surtaxePrspTaux = 0;
    }
}