export class EnterRSP {
    entreeImportId: string;
    noEntree: number | null;
    noLettreTransport: string;
    recuPalan: string;
    rspInt: number | null;
    nbrePalette: number | null;
    nbreEtiquette: number | null;
    noConteneur: string;
    provenanceId: number | null;
    bargeId: number | null;
    transitaireId: number | null;
    importateurId: number | null;
    nif: string;
    transporteur: string;
    marchandiseId: number | null;
    emballageId: number | null;
    typeConditionId: string;
    typeTransport: string;
    dateEntree: Date | null;
    nbreColis: number | null;
    poids: number | null;
    montant: number | null;
    destinationId: number | null;
    entreposId: number | null;
    peseMagasin: boolean;
    montantPeseMagasin: number | null;
    faireSuivre: boolean;
    montantFaireSuivre: number | null;
    qteLt: number | null;
    poidsLt: number | null;
    fraisSlt: number | null;
    fraisSrsp: number | null;
    surtaxeCrsp: number | null;
    surtaxeClt: number | null;
    surtaxePlt: number | null;
    surtaxePrsp: number | null;
    pvId: number | null;
    penalite: number | null;
    montantLt: number | null;
    montantRsp: number | null;
    taxe: number | null;
    fraisPompageRsp: number | null;
    montantCamion: number | null;
    montantBarge: number | null;
    tarifCamion: number | null;
    tarifBarge: number | null;
    numConteneur: string;
    fraisArrimage: number | null;
    doubleManut: boolean;
    exonere: boolean;
    transit: boolean;
    dossier: string;
    declarant: string;
    observation: string;
    constatation: string;
    colisManquants: string;
    colisAvaries: string;
    plaque: string;
    dateCreation: Date | null;
    userCreation: string;
    dateUpdate: Date | null;
    userUpdate: string;

    constructor() {
        this.entreeImportId = '';
        this.noEntree = null;
        this.noLettreTransport = '';
        this.recuPalan = '';
        this.rspInt = null;
        this.nbrePalette = null;
        this.nbreEtiquette = null;
        this.noConteneur = '';
        this.provenanceId = null;
        this.bargeId = null;
        this.transitaireId = null;
        this.importateurId = null;
        this.nif = '';
        this.transporteur = '';
        this.marchandiseId = null;
        this.emballageId = null;
        this.typeConditionId = '';
        this.typeTransport = '';
        this.dateEntree = null;
        this.nbreColis = null;
        this.poids = null;
        this.montant = null;
        this.destinationId = null;
        this.entreposId = null;
        this.peseMagasin = false;
        this.montantPeseMagasin = null;
        this.faireSuivre = false;
        this.montantFaireSuivre = null;
        this.qteLt = null;
        this.poidsLt = null;
        this.fraisSlt = null;
        this.fraisSrsp = null;
        this.surtaxeCrsp = null;
        this.surtaxeClt = null;
        this.surtaxePlt = null;
        this.surtaxePrsp = null;
        this.pvId = null;
        this.penalite = null;
        this.montantLt = null;
        this.montantRsp = null;
        this.taxe = null;
        this.fraisPompageRsp = null;
        this.montantCamion = null;
        this.montantBarge = null;
        this.tarifCamion = null;
        this.tarifBarge = null;
        this.numConteneur = '';
        this.fraisArrimage = null;
        this.doubleManut = false;
        this.exonere = false;
        this.transit = false;
        this.dossier = '';
        this.declarant = '';
        this.observation = '';
        this.constatation = '';
        this.colisManquants = '';
        this.colisAvaries = '';
        this.plaque = '';
        this.dateCreation = null;
        this.userCreation = '';
        this.dateUpdate = null;
        this.userUpdate = '';
    }
}