export class Remorquage {
    noRemorque: string;
    lettreTransp: string;
    bargeId: number | null;
    longeur: number | null;
    largeur: number | null;
    tirant: number | null;
    dateDebut: Date | null;
    dateFin: Date | null;
    montant: number | null;
    importateurId: number | null;
    manoeuvre: number | null;
    declarant: string;
    userCreation: string;
    dateCreation: Date | null;
    valide1: boolean;
    valide2: boolean;
    userValide1: string;
    userValide2: string;
    userUpdate: string;
    dateUpdate: Date | null;
    dossierId: string;
    modePayement: string;
    isValid: boolean;
    dateValidation: Date | null;
    montantRedev: number | null;
    montRedevTaxe: number | null;
    montTVA: number | null;
    taxe: boolean;
    nbreBateau: number | null;
    refAnnule: string;
    numeroOrdre: number | null;
    factureSignature: string;
    motifAnnulation: string;

    constructor() {
        this.noRemorque = '';
        this.lettreTransp = '';
        this.bargeId = null;
        this.longeur = null;
        this.largeur = null;
        this.tirant = null;
        this.dateDebut = new Date();
        this.dateFin = new Date();
        this.montant = 0;
        this.importateurId = null;
        this.manoeuvre = null;
        this.declarant = '';
        this.userCreation = '';
        this.dateCreation = null;
        this.valide1 = false;
        this.valide2 = false;
        this.userValide1 = '';
        this.userValide2 = '';
        this.userUpdate = '';
        this.dateUpdate = null;
        this.dossierId = 'GPS';
        this.modePayement = '';
        this.isValid = false;
        this.dateValidation = null;
        this.montantRedev = 0;
        this.montRedevTaxe = 0;
        this.montTVA = 0;
        this.taxe = false;
        this.nbreBateau = 1;
        this.refAnnule = '';
        this.numeroOrdre = null;
        this.factureSignature = '';
        this.motifAnnulation = '';
    }
}