// FacFactureSortie.ts
export class FacFactureSortie {
    factureSortieId: number | null;
    sortieId: string;
    numFacture: string;
    rsp: string;
    lt: string;
    manutBateau: number | null;
    manutCamion: number | null;
    surtaxeColisLourd: number | null;
    montSalissage: number | null;
    montArrimage: number | null;
    montRedev: number | null;
    montPalette: number | null;
    montPesMag: number | null;
    montLais: number | null;
    peage: number | null;
    montEtiquette: number | null;
    montFixationPlaque: number | null;
    montTotalManut: number | null;
    montMagasinage: number | null;
    montGardienage: number | null;
    montTVA: number | null;
    montantPaye: number | null;
    dateSortie: Date | null;
    userCreation: string;
    marchandiseId: number | null;
    clientId: number | null;
    exonere: boolean;
    declarant: string;
    dossierId: string;
    modePayement: string;
    isValid: boolean;
    dateValidation: Date | null;
    refAnnule: string;
    numeroOrdre: number | null;
    annule: boolean;
    montantReduction: number | null;
    tauxReduction: number | null;
    factureSignature: string;
    motifAnnulation: string;

    constructor() {
        this.factureSortieId = null;
        this.sortieId = '';
        this.numFacture = '';
        this.rsp = '';
        this.lt = '';
        this.manutBateau = null;
        this.manutCamion = null;
        this.surtaxeColisLourd = null;
        this.montSalissage = null;
        this.montArrimage = null;
        this.montRedev = null;
        this.montPalette = null;
        this.montPesMag = null;
        this.montLais = null;
        this.peage = null;
        this.montEtiquette = null;
        this.montFixationPlaque = null;
        this.montTotalManut = null;
        this.montMagasinage = null;
        this.montGardienage = null;
        this.montTVA = null;
        this.montantPaye = null;
        this.dateSortie = null;
        this.userCreation = '';
        this.marchandiseId = null;
        this.clientId = null;
        this.exonere = false;
        this.declarant = '';
        this.dossierId = '';
        this.modePayement = '';
        this.isValid = false;
        this.dateValidation = null;
        this.refAnnule = '';
        this.numeroOrdre = null;
        this.annule = false;
        this.montantReduction = null;
        this.tauxReduction = null;
        this.factureSignature = '';
        this.motifAnnulation = '';
    }
}